---
title: "Letter Dated Feb 05, 2023"
author: "Arvind Venkatadri"
editor: visual
categories:
  - news
  - career
  - education
---

Dear Chubbu!

Yesterday you came up to me in the morning and stood there in a
"significant" way, like you used to as small child and were waiting for
my response to a particularly clever answer you had just given.

I...was preoccupied. There was Paati, your grandmother who needed
surgery very quickly. I was moving her to the larger Guest Bedroom,
closer to the door and in the quietest part of the house. And there was
furniture to move and her clothes....so, just heard you say you had made
it to the [Prague Film School](https://www.praguefilmschool.cz/) and
here I was too frazzled to listen. And I probably made it worse by
asking you to help me shift the furniture and snapping at you too, when
I could not get you to do exactly what I wanted you to do.

There is nothing left to say...except that I really should have paid
more attention to you. And I still can't believe it that you are going
further away in a short while.

That night you were excited enough to get your friend Srinidhi to get
started with her application process. You both worked late into the
night, preparing applications, SOPs and other documents. In the morning
I could see the tell-tale "shoemaker and the elves" signs of midnight
food-making in the kitchen !!

Signs of Dreams.
