project:
  type: website
  preview:
    port: 2100
    browser: true
website: 
  title: "Letters to My Daughter"
  page-navigation: true
  site-url: "https://letters-to-my-daughter.netlify.app/"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts/posts.qmd
        text: Letters

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
